version = 0.1

[default]
[default.global.parameters]
stack_name = "aws-nest-roles-api"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
stack_name = "aws-nest-roles-api"
s3_prefix = "aws-nest-roles-api"
region = "sa-east-1"
parameter_overrides = "Stage=dev"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.deploy.parameters]
stack_name = "aws-nest-roles-api-dev-v2"
region = "sa-east-1"
resolve_s3 = true
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"

[prod]
[prod.deploy.parameters]
stack_name = "aws-nest-roles-api-prod-v2"
region = "sa-east-1"
resolve_s3 = true
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"