name: Build and Package Application

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate configuration
        run: |
          # Como ajv-cli ainda não está configurado, vamos pular por enquanto
          echo "⏭️  Pulando validação de configuração por enquanto"

      - name: Build application
        run: npm run build:prod

      - name: Create artifact
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          tar -czf nest-roles-app-${COMMIT_SHA}.tar.gz dist/ app.config.json package.json
          echo "ARTIFACT_NAME=nest-roles-app-${COMMIT_SHA}.tar.gz" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Upload artifact to S3
        run: |
          aws s3 cp ${{ env.ARTIFACT_NAME }} \
            s3://company-artifacts/nest-roles-app/${{ env.ARTIFACT_NAME }}

      - name: Trigger Infrastructure Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          repository: ${{ github.repository_owner }}/nest-roles-infra
          event-type: deploy-application
          client-payload: |
            {
              "artifact": "${{ env.ARTIFACT_NAME }}",
              "environment": "dev",
              "commit_sha": "${{ github.sha }}",
              "triggered_by": "${{ github.actor }}"
            }

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            🚀 **Deploy automático realizado**

            **Aplicação:** nest-roles-app
            **Commit:** ${{ github.sha }}
            **Artefato:** ${{ env.ARTIFACT_NAME }}
            **Ambiente:** dev

            **Mudanças incluídas:**
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
